import { Link } from "react-router-dom";
import styles from "./MusicLicensePage.module.css";

export function MusicLicensePage() {
  return <div className={styles.page}>
    <header><Link to="/">Make It a Story</Link></header>
    <main>
      <p className={styles.eyebrow}>Storyteller Generated Music License · version 1.0</p>
      <h1>Use your generated soundtrack anywhere.</h1>
      <p className={styles.lead}>This license applies to music generated by Make It a Story’s built-in procedural soundtrack engine.</p>
      <section><h2>Your permission</h2><p>We grant you a perpetual, worldwide, royalty-free, non-exclusive license to use, copy, edit, distribute, synchronize, publish, and monetize the generated music for commercial or non-commercial purposes, inside or outside Make It a Story. Attribution is not required.</p></section>
      <section><h2>What is not included</h2><p>The license does not cover your source video, uploaded audio, narration, or any other third-party material. Generated music is non-exclusive and is not guaranteed to be unique.</p></section>
      <section><h2>Content ID and exclusive claims</h2><p>You may not register the generated music by itself in Content ID or another automated rights-management system, and you may not claim exclusive ownership of it. This protects other people who may receive music produced from the same presets.</p></section>
      <section><h2>How it is made</h2><p>The built-in engine synthesizes tones and percussion from oscillators, noise, and envelopes. It does not incorporate third-party recordings, audio samples, pretrained music models, or an external music-generation service. Each download includes reproducible provenance metadata.</p></section>
      <p className={styles.note}>This permission is tied to license version <code>storyteller-generated-music-1.0</code>, recorded in the soundtrack provenance.</p>
    </main>
  </div>;
}
