import type { Locale } from "@storyteller/localization";

const copies = {
  en: {
    scenes: "Scenes", addScene: "Add scene", scene: "Scene", timeline: "Timeline", editorModes: "Editor mode", emptyScene: "Start by adding a photo or video",
    materials: "Materials", addMaterial: "Upload materials", uploadingMaterials: "Uploading {{count}}…",
    portrait: "Portrait", landscape: "Landscape", silent: "Silent", audioUnclassified: "Audio needs labels", voice: "Voice", music: "Music", ambient: "Background sound",
    layout: "Composition", layoutHint: "Options follow the orientation sequence", settings: "Settings", motion: "Movement", duration: "Duration",
    animationType: "Animation type", animationTypeHint: "Choose how the still image comes alive", zoom: "Zoom", zoomRendererHint: "Camera movement around the still image",
    aiAnimation: "AI animation", aiAnimationHint: "Text instruction or a ready-made preset", comingSoon: "Soon", textPrompt: "Text prompt", presets: "Presets",
    cameraMovement: "Camera movement", zoomDirectionHint: "Choose the direction of the zoom", panDirectionHint: "Choose the direction of the camera pan",
    focusPoint: "Focus point", moveFocusPoint: "Drag to move the focus point",
    seconds: "sec", preview: "Scene preview",
    zoomIn: "Zoom in", zoomOut: "Zoom out", panLeft: "Right → left", panRight: "Left → right", noMotion: "No added motion",
    creatingScene: "Creating scene…", emptyPipelineHint: "No scenes yet. Add one in the pipeline on the left.",
    sceneCreateError: "Could not create the scene. Check that the API is running and try again.", operationError: "The change was not saved. Try again.",
    sceneOrderChanged: "The story changed elsewhere. The previous order was restored and the current story was loaded.",
    sceneOrderError: "The scene order was not saved. The previous order was restored.",
    materialMoveChanged: "The story changed elsewhere. The material was left in its original scene and the current story was loaded.",
    materialMoveError: "The material was not moved. It remains in its original scene.",
    uploadTooLarge: "The file is larger than the allowed upload size.", uploadUnsupported: "This photo or video format is not supported.",
    uploadUnreadable: "The photo or video could not be read. Check that the file plays and try again.",
    fileInfo: "File information", fileName: "Name", fileSize: "Size", fileFormat: "Format", fileDimensions: "Dimensions", fileDuration: "Duration", sourceAudio: "Source audio",
    sceneDebug: "Scene debug data", materialActions: "Material actions", editMaterial: "Edit material", cropMaterial: "Crop", trimMaterial: "Trim video",
    rotateMaterial: "Rotate", rotateLeft: "Rotate left", rotateRight: "Rotate right", originalFrame: "Full frame", squareFrame: "Square 1:1",
    verticalFrame: "Vertical 9:16", horizontalFrame: "Horizontal 16:9", resetEditing: "Reset", cropArea: "Crop area",
    cropResult: "Result: {{width}} × {{height}}", applyChanges: "Apply", applyingChanges: "Applying…", materialEditError: "Could not apply the edits. Try again.",
    trimStart: "Start", trimEnd: "End", selectedDuration: "Selected: {{duration}} sec", playSelection: "Play selection", pauseVideo: "Pause",
    videoPosition: "Video position", videoEditPreview: "Video editing preview", videoPlaybackError: "Could not play this video.",
    videoDurationUnavailable: "Video duration is not available yet.",
    audioWaveform: "Audio waveform", waveformLoading: "Loading waveform…", waveformUnavailable: "Waveform unavailable",
    deleteMaterial: "Delete material", deleteMaterialConfirmation: "Delete “{{name}}” from this scene? The uploaded file will also be deleted.", cancel: "Cancel",
    deleteScene: "Delete scene", deleteSceneTitle: "Delete “{{name}}”?", confirmDeleteScene: "Delete", deletingScene: "Please wait…",
    deleteSceneConfirmation: "The scene and its files will be permanently deleted. Files used by other scenes in this story will be kept.",
    sceneDeleteChanged: "The story has changed. Close this dialog, review the scene and confirm again.",
    sceneDeleteBlocked: "The story cannot be edited in its current state. Close this dialog and try again later.",
    sceneDeleteError: "The scene was not deleted. You can try again.",
    sceneDeleteUnverified: "Could not verify whether the scene was deleted. Check its status before trying again.", checkSceneDeletion: "Check status",
    materialEditorHint: "Non-destructive editing tools will be added here.", dragMaterial: "Drag material {{number}}", dragMaterialHint: "Drag to reorder or drop on another scene. The arrow keys reorder within this scene.",
    dragScene: "Reorder scene {{number}}", dragSceneHint: "Drag to reorder. Use the up and down arrow keys with a keyboard.", close: "Close",
    createScene: "Create scene", createCover: "Create cover", coverEditorPending: "The cover will open in a separate editor later.",
    storyStart: "Start of the story", storyEnd: "End of the story", noScenes: "No scenes yet", sceneEdgeHint: "Continue the story or prepare its cover.",
    sceneCarousel: "Story scenes", swipeScenes: "Swipe left or right to change scenes", sceneTools: "Scene tools",
    allStories: "All stories", untitledStory: "Untitled story", saving: "Saving", saved: "Saved", openScene: "Open scene",
    downloadScene: "Download scene", renderingScene: "Rendering scene…", renderSceneError: "Could not render the scene. Try again.",
    renderVersions: "Saved versions", versionCurrent: "Current", versionStale: "Outdated",
    renderUnsupported: "Downloads currently support scenes with one photo or video.",
    renderVersionsHint: "Only affected results are rebuilt. Downloads always use the current edit.",
    renderVersionChanged: "The scene changed. Download again to build the current version.",
    versionQueued: "Queued", versionReady: "Ready", versionFailed: "Not completed", versionLoading: "Loading versions…",
    versionLoadError: "Could not check versions. Try again shortly.", versionEmpty: "No saved versions yet.", versionDetails: "Version details",
    downloadVideo: "Video only", downloadAudio: "Audio only", downloadCombined: "Video with audio",
    noAudioTrack: "This video has no audio track.", downloadPreparedFile: "Download prepared file", muteVideo: "Mute", unmuteVideo: "Unmute",
    renderQueueTimeout: "Rendering did not start. Check that the render worker is running and try again.",
    renderSceneTimeout: "Rendering is taking too long. Try downloading again shortly.",
  },
  ru: {
    scenes: "Сцены", addScene: "Добавить сцену", scene: "Сцена", timeline: "Таймлайн", editorModes: "Режим редактора", emptyScene: "Добавьте фотографию или видео",
    materials: "Материалы", addMaterial: "Загрузить материалы", uploadingMaterials: "Загружаем: {{count}}…",
    portrait: "Портрет", landscape: "Альбом", silent: "Без звука", audioUnclassified: "Звук нужно разметить", voice: "Голос", music: "Музыка", ambient: "Фоновый звук",
    layout: "Композиция", layoutHint: "Варианты зависят от последовательности ориентаций", settings: "Настройки", motion: "Движение", duration: "Длительность",
    animationType: "Тип анимации", animationTypeHint: "Выберите, как оживить фотографию", zoom: "Zoom", zoomRendererHint: "Движение камеры по фотографии",
    aiAnimation: "AI-анимация", aiAnimationHint: "Текстовая инструкция или готовый пресет", comingSoon: "Скоро", textPrompt: "Инструкция", presets: "Пресеты",
    cameraMovement: "Движение камеры", zoomDirectionHint: "Выберите направление зума", panDirectionHint: "Выберите направление движения камеры",
    focusPoint: "Точка фокуса", moveFocusPoint: "Перетащить точку фокуса",
    seconds: "сек", preview: "Предпросмотр сцены",
    zoomIn: "Приближение", zoomOut: "Отдаление", panLeft: "Справа → налево", panRight: "Слева → направо", noMotion: "Без движения",
    creatingScene: "Создаём сцену…", emptyPipelineHint: "Сцен пока нет. Добавьте сцену в pipeline слева.",
    sceneCreateError: "Не удалось создать сцену. Проверьте, что API запущен, и попробуйте ещё раз.", operationError: "Изменение не сохранилось. Попробуйте ещё раз.",
    sceneOrderChanged: "История изменилась в другом окне. Прежний порядок восстановлен, актуальная история загружена.",
    sceneOrderError: "Порядок сцен не сохранился. Прежний порядок восстановлен.",
    materialMoveChanged: "История изменилась в другом окне. Материал оставлен в исходной сцене, актуальная история загружена.",
    materialMoveError: "Материал не перенесён и остался в исходной сцене.",
    uploadTooLarge: "Файл превышает допустимый размер загрузки.", uploadUnsupported: "Этот формат фотографии или видео не поддерживается.",
    uploadUnreadable: "Не удалось прочитать фотографию или видео. Проверьте, что файл воспроизводится, и попробуйте ещё раз.",
    fileInfo: "Информация о файле", fileName: "Название", fileSize: "Размер", fileFormat: "Формат", fileDimensions: "Разрешение", fileDuration: "Длительность", sourceAudio: "Исходный звук",
    sceneDebug: "Отладочные данные сцены", materialActions: "Действия с материалом", editMaterial: "Редактировать материал", cropMaterial: "Кадрировать", trimMaterial: "Обрезать видео",
    rotateMaterial: "Повернуть", rotateLeft: "Повернуть влево", rotateRight: "Повернуть вправо", originalFrame: "Весь кадр", squareFrame: "Квадрат 1:1",
    verticalFrame: "Вертикаль 9:16", horizontalFrame: "Горизонталь 16:9", resetEditing: "Сбросить", cropArea: "Область кадрирования",
    cropResult: "Результат: {{width}} × {{height}}", applyChanges: "Применить", applyingChanges: "Применяем…", materialEditError: "Не удалось применить изменения. Попробуйте ещё раз.",
    trimStart: "Начало", trimEnd: "Конец", selectedDuration: "Выбрано: {{duration}} сек", playSelection: "Проиграть фрагмент", pauseVideo: "Пауза",
    videoPosition: "Позиция в видео", videoEditPreview: "Предпросмотр редактирования видео", videoPlaybackError: "Не удалось воспроизвести видео.",
    videoDurationUnavailable: "Длительность видео пока недоступна.",
    audioWaveform: "Звуковая волна", waveformLoading: "Строим звуковую волну…", waveformUnavailable: "Звуковая волна недоступна",
    deleteMaterial: "Удалить материал", deleteMaterialConfirmation: "Удалить «{{name}}» из сцены? Загруженный файл также будет удалён.", cancel: "Отмена",
    deleteScene: "Удалить сцену", deleteSceneTitle: "Удалить «{{name}}»?", confirmDeleteScene: "Удалить", deletingScene: "Подождите…",
    deleteSceneConfirmation: "Сцена и её файлы будут удалены без возможности восстановления. Файлы, используемые в других сценах этой истории, сохранятся.",
    sceneDeleteChanged: "История изменилась. Закройте окно, проверьте сцену и подтвердите удаление заново.",
    sceneDeleteBlocked: "Сейчас эту историю нельзя редактировать. Закройте окно и попробуйте позже.",
    sceneDeleteError: "Сцена не удалена. Можно попробовать ещё раз.",
    sceneDeleteUnverified: "Не удалось проверить, удалена ли сцена. Проверьте её состояние перед повторной попыткой.", checkSceneDeletion: "Проверить состояние",
    materialEditorHint: "Здесь появятся инструменты неразрушающего редактирования.", dragMaterial: "Перетащить материал {{number}}", dragMaterialHint: "Меняйте порядок или перенесите материал на другую сцену. Стрелки меняют порядок внутри текущей сцены.",
    dragScene: "Изменить порядок сцены {{number}}", dragSceneHint: "Перетащите для изменения порядка. С клавиатуры используйте стрелки вверх и вниз.", close: "Закрыть",
    createScene: "Создать сцену", createCover: "Создать обложку", coverEditorPending: "Обложка позже откроется в отдельном редакторе.",
    storyStart: "Начало истории", storyEnd: "Конец истории", noScenes: "Сцен пока нет", sceneEdgeHint: "Продолжите историю или подготовьте её обложку.",
    sceneCarousel: "Сцены истории", swipeScenes: "Смахните влево или вправо, чтобы сменить сцену", sceneTools: "Инструменты сцены",
    allStories: "Все истории", untitledStory: "История без названия", saving: "Сохраняем", saved: "Сохранено", openScene: "Открыть сцену",
    downloadScene: "Скачать сцену", renderingScene: "Рендерим сцену…", renderSceneError: "Не удалось отрендерить сцену. Попробуйте ещё раз.",
    renderVersions: "Сохранённые версии", versionCurrent: "Актуальна", versionStale: "Устарела",
    renderUnsupported: "Скачивание пока доступно для сцены с одним фото или видео.",
    renderVersionsHint: "Пересобираются только затронутые результаты. Скачивание всегда учитывает текущие правки.",
    renderVersionChanged: "Сцена изменилась. Повторите скачивание, чтобы собрать актуальную версию.",
    versionQueued: "В очереди", versionReady: "Готова", versionFailed: "Не завершена", versionLoading: "Загружаем версии…",
    versionLoadError: "Не удалось проверить версии. Попробуйте чуть позже.", versionEmpty: "Сохранённых версий пока нет.", versionDetails: "Данные версии",
    downloadVideo: "Только видео", downloadAudio: "Только аудио", downloadCombined: "Видео со звуком",
    noAudioTrack: "В этом видео нет аудиодорожки.", downloadPreparedFile: "Скачать готовый файл", muteVideo: "Выключить звук", unmuteVideo: "Включить звук",
    renderQueueTimeout: "Рендер не начался. Проверьте, что обработчик рендера запущен, и попробуйте ещё раз.",
    renderSceneTimeout: "Рендер занимает слишком много времени. Попробуйте скачать сцену чуть позже.",
  },
  "sr-Latn": {
    scenes: "Scene", addScene: "Dodaj scenu", scene: "Scena", timeline: "Vremenska linija", editorModes: "Režim uređivača", emptyScene: "Dodajte fotografiju ili video",
    materials: "Materijali", addMaterial: "Otpremi materijale", uploadingMaterials: "Otpremanje: {{count}}…",
    portrait: "Portret", landscape: "Pejzaž", silent: "Bez zvuka", audioUnclassified: "Zvuk treba označiti", voice: "Glas", music: "Muzika", ambient: "Pozadinski zvuk",
    layout: "Kompozicija", layoutHint: "Opcije prate redosled orijentacija", settings: "Podešavanja", motion: "Kretanje", duration: "Trajanje",
    animationType: "Vrsta animacije", animationTypeHint: "Izaberite kako fotografija oživljava", zoom: "Zoom", zoomRendererHint: "Kretanje kamere po fotografiji",
    aiAnimation: "AI animacija", aiAnimationHint: "Tekstualno uputstvo ili gotov preset", comingSoon: "Uskoro", textPrompt: "Uputstvo", presets: "Preseti",
    cameraMovement: "Kretanje kamere", zoomDirectionHint: "Izaberite smer zumiranja", panDirectionHint: "Izaberite smer kretanja kamere",
    focusPoint: "Tačka fokusa", moveFocusPoint: "Prevucite tačku fokusa",
    seconds: "sek", preview: "Pregled scene",
    zoomIn: "Zumiraj", zoomOut: "Odumiraj", panLeft: "Zdesna → nalevo", panRight: "Sleva → nadesno", noMotion: "Bez dodatnog kretanja",
    creatingScene: "Kreiranje scene…", emptyPipelineHint: "Još nema scena. Dodajte scenu u pipeline-u levo.",
    sceneCreateError: "Scena nije kreirana. Proverite da li API radi i pokušajte ponovo.", operationError: "Promena nije sačuvana. Pokušajte ponovo.",
    sceneOrderChanged: "Priča je promenjena u drugom prozoru. Prethodni redosled je vraćen i učitana je aktuelna priča.",
    sceneOrderError: "Redosled scena nije sačuvan. Prethodni redosled je vraćen.",
    materialMoveChanged: "Priča je promenjena u drugom prozoru. Materijal je ostao u izvornoj sceni i učitana je aktuelna priča.",
    materialMoveError: "Materijal nije premešten i ostao je u izvornoj sceni.",
    uploadTooLarge: "Datoteka prelazi dozvoljenu veličinu otpremanja.", uploadUnsupported: "Ovaj format fotografije ili videa nije podržan.",
    uploadUnreadable: "Fotografija ili video nisu mogli da se pročitaju. Proverite da li se datoteka reprodukuje i pokušajte ponovo.",
    fileInfo: "Informacije o datoteci", fileName: "Naziv", fileSize: "Veličina", fileFormat: "Format", fileDimensions: "Dimenzije", fileDuration: "Trajanje", sourceAudio: "Izvorni zvuk",
    sceneDebug: "Podaci scene za otklanjanje grešaka", materialActions: "Radnje materijala", editMaterial: "Uredi materijal", cropMaterial: "Iseci kadar", trimMaterial: "Skrati video",
    rotateMaterial: "Rotiraj", rotateLeft: "Rotiraj ulevo", rotateRight: "Rotiraj udesno", originalFrame: "Ceo kadar", squareFrame: "Kvadrat 1:1",
    verticalFrame: "Uspravno 9:16", horizontalFrame: "Vodoravno 16:9", resetEditing: "Poništi", cropArea: "Oblast isecanja",
    cropResult: "Rezultat: {{width}} × {{height}}", applyChanges: "Primeni", applyingChanges: "Primena…", materialEditError: "Promene nisu primenjene. Pokušajte ponovo.",
    trimStart: "Početak", trimEnd: "Kraj", selectedDuration: "Izabrano: {{duration}} sek", playSelection: "Pusti odlomak", pauseVideo: "Pauza",
    videoPosition: "Pozicija u videu", videoEditPreview: "Pregled uređivanja videa", videoPlaybackError: "Video ne može da se reprodukuje.",
    videoDurationUnavailable: "Trajanje videa još nije dostupno.",
    audioWaveform: "Zvučni talas", waveformLoading: "Učitavanje zvučnog talasa…", waveformUnavailable: "Zvučni talas nije dostupan",
    deleteMaterial: "Obriši materijal", deleteMaterialConfirmation: "Obrisati „{{name}}“ iz scene? Otpremljena datoteka će takođe biti obrisana.", cancel: "Otkaži",
    deleteScene: "Obriši scenu", deleteSceneTitle: "Obrisati „{{name}}“?", confirmDeleteScene: "Obriši", deletingScene: "Sačekajte…",
    deleteSceneConfirmation: "Scena i njene datoteke biće trajno obrisane. Datoteke koje se koriste u drugim scenama ove priče biće sačuvane.",
    sceneDeleteChanged: "Priča je promenjena. Zatvorite ovaj prozor, proverite scenu i potvrdite ponovo.",
    sceneDeleteBlocked: "Priču trenutno nije moguće uređivati. Zatvorite ovaj prozor i pokušajte kasnije.",
    sceneDeleteError: "Scena nije obrisana. Možete pokušati ponovo.",
    sceneDeleteUnverified: "Nije moguće proveriti da li je scena obrisana. Proverite status pre novog pokušaja.", checkSceneDeletion: "Proveri status",
    materialEditorHint: "Ovde će biti dodati alati za nedestruktivno uređivanje.", dragMaterial: "Prevuci materijal {{number}}", dragMaterialHint: "Prevucite za promenu redosleda ili spustite na drugu scenu. Strelice menjaju redosled unutar trenutne scene.",
    dragScene: "Promeni redosled scene {{number}}", dragSceneHint: "Prevucite za promenu redosleda. Koristite strelice gore i dole na tastaturi.", close: "Zatvori",
    createScene: "Napravi scenu", createCover: "Napravi naslovnicu", coverEditorPending: "Naslovnica će se kasnije otvarati u posebnom editoru.",
    storyStart: "Početak priče", storyEnd: "Kraj priče", noScenes: "Još nema scena", sceneEdgeHint: "Nastavite priču ili pripremite naslovnicu.",
    sceneCarousel: "Scene priče", swipeScenes: "Prevucite levo ili desno za promenu scene", sceneTools: "Alati scene",
    allStories: "Sve priče", untitledStory: "Priča bez naslova", saving: "Čuvanje", saved: "Sačuvano", openScene: "Otvori scenu",
    downloadScene: "Preuzmi scenu", renderingScene: "Renderovanje scene…", renderSceneError: "Scena nije renderovana. Pokušajte ponovo.",
    renderVersions: "Sačuvane verzije", versionCurrent: "Aktuelna", versionStale: "Zastarela",
    renderUnsupported: "Preuzimanje je trenutno dostupno za scene sa jednom fotografijom ili videom.",
    renderVersionsHint: "Ponovo se obrađuju samo izmenjeni rezultati. Preuzimanje uvek prati trenutne izmene.",
    renderVersionChanged: "Scena je izmenjena. Ponovite preuzimanje da biste napravili aktuelnu verziju.",
    versionQueued: "Na čekanju", versionReady: "Spremna", versionFailed: "Nije završena", versionLoading: "Učitavanje verzija…",
    versionLoadError: "Nije moguće proveriti verzije. Pokušajte ponovo uskoro.", versionEmpty: "Još nema sačuvanih verzija.", versionDetails: "Detalji verzije",
    downloadVideo: "Samo video", downloadAudio: "Samo zvuk", downloadCombined: "Video sa zvukom",
    noAudioTrack: "Ovaj video nema zvučni zapis.", downloadPreparedFile: "Preuzmi pripremljenu datoteku", muteVideo: "Isključi zvuk", unmuteVideo: "Uključi zvuk",
    renderQueueTimeout: "Renderovanje nije počelo. Proverite da li je servis za renderovanje pokrenut i pokušajte ponovo.",
    renderSceneTimeout: "Renderovanje traje predugo. Pokušajte ponovo da preuzmete scenu uskoro.",
  },
  es: {
    scenes: "Escenas", addScene: "Añadir escena", scene: "Escena", timeline: "Línea de tiempo", editorModes: "Modo del editor", emptyScene: "Empieza añadiendo una foto o un vídeo",
    materials: "Materiales", addMaterial: "Subir materiales", uploadingMaterials: "Subiendo {{count}}…",
    portrait: "Vertical", landscape: "Horizontal", silent: "Sin sonido", audioUnclassified: "El audio necesita etiquetas", voice: "Voz", music: "Música", ambient: "Sonido ambiente",
    layout: "Composición", layoutHint: "Las opciones siguen la secuencia de orientaciones", settings: "Ajustes", motion: "Movimiento", duration: "Duración",
    animationType: "Tipo de animación", animationTypeHint: "Elige cómo cobra vida la imagen fija", zoom: "Zoom", zoomRendererHint: "Movimiento de cámara sobre la imagen fija",
    aiAnimation: "Animación con IA", aiAnimationHint: "Instrucción de texto o preajuste listo para usar", comingSoon: "Próximamente", textPrompt: "Instrucción de texto", presets: "Preajustes",
    cameraMovement: "Movimiento de cámara", zoomDirectionHint: "Elige la dirección del zoom", panDirectionHint: "Elige la dirección del desplazamiento de cámara",
    focusPoint: "Punto de enfoque", moveFocusPoint: "Arrastra para mover el punto de enfoque",
    seconds: "s", preview: "Vista previa de la escena",
    zoomIn: "Acercar", zoomOut: "Alejar", panLeft: "Derecha → izquierda", panRight: "Izquierda → derecha", noMotion: "Sin movimiento añadido",
    creatingScene: "Creando la escena…", emptyPipelineHint: "Todavía no hay escenas. Añade una en la secuencia de la izquierda.",
    sceneCreateError: "No se pudo crear la escena. Comprueba que la API esté en ejecución e inténtalo de nuevo.", operationError: "El cambio no se guardó. Inténtalo de nuevo.",
    sceneOrderChanged: "La historia cambió en otro lugar. Se restauró el orden anterior y se cargó la historia actual.",
    sceneOrderError: "El orden de las escenas no se guardó. Se restauró el orden anterior.",
    materialMoveChanged: "La historia cambió en otro lugar. El material permaneció en su escena original y se cargó la historia actual.",
    materialMoveError: "El material no se movió. Permanece en su escena original.",
    uploadTooLarge: "El archivo supera el tamaño de subida permitido.", uploadUnsupported: "Este formato de foto o vídeo no es compatible.",
    uploadUnreadable: "No se pudo leer la foto o el vídeo. Comprueba que el archivo se reproduzca e inténtalo de nuevo.",
    fileInfo: "Información del archivo", fileName: "Nombre", fileSize: "Tamaño", fileFormat: "Formato", fileDimensions: "Dimensiones", fileDuration: "Duración", sourceAudio: "Audio original",
    sceneDebug: "Datos de depuración de la escena", materialActions: "Acciones del material", editMaterial: "Editar material", cropMaterial: "Recortar imagen", trimMaterial: "Recortar vídeo",
    rotateMaterial: "Girar", rotateLeft: "Girar a la izquierda", rotateRight: "Girar a la derecha", originalFrame: "Fotograma completo", squareFrame: "Cuadrado 1:1",
    verticalFrame: "Vertical 9:16", horizontalFrame: "Horizontal 16:9", resetEditing: "Restablecer", cropArea: "Área de recorte",
    cropResult: "Resultado: {{width}} × {{height}}", applyChanges: "Aplicar", applyingChanges: "Aplicando…", materialEditError: "No se pudieron aplicar los cambios. Inténtalo de nuevo.",
    trimStart: "Inicio", trimEnd: "Fin", selectedDuration: "Selección: {{duration}} s", playSelection: "Reproducir selección", pauseVideo: "Pausar",
    videoPosition: "Posición del vídeo", videoEditPreview: "Vista previa de la edición de vídeo", videoPlaybackError: "No se pudo reproducir este vídeo.",
    videoDurationUnavailable: "La duración del vídeo aún no está disponible.",
    audioWaveform: "Forma de onda de audio", waveformLoading: "Cargando la forma de onda…", waveformUnavailable: "Forma de onda no disponible",
    deleteMaterial: "Eliminar material", deleteMaterialConfirmation: "¿Eliminar «{{name}}» de esta escena? También se eliminará el archivo subido.", cancel: "Cancelar",
    deleteScene: "Eliminar escena", deleteSceneTitle: "¿Eliminar «{{name}}»?", confirmDeleteScene: "Eliminar", deletingScene: "Espera…",
    deleteSceneConfirmation: "La escena y sus archivos se eliminarán de forma permanente. Se conservarán los archivos utilizados por otras escenas de esta historia.",
    sceneDeleteChanged: "La historia ha cambiado. Cierra este cuadro, revisa la escena y vuelve a confirmar.",
    sceneDeleteBlocked: "La historia no se puede editar en su estado actual. Cierra este cuadro e inténtalo de nuevo más tarde.",
    sceneDeleteError: "La escena no se eliminó. Puedes intentarlo de nuevo.",
    sceneDeleteUnverified: "No se pudo comprobar si la escena se eliminó. Revisa su estado antes de intentarlo de nuevo.", checkSceneDeletion: "Comprobar estado",
    materialEditorHint: "Aquí se añadirán herramientas de edición no destructiva.", dragMaterial: "Arrastrar material {{number}}", dragMaterialHint: "Arrastra para cambiar el orden o suéltalo en otra escena. Las teclas de flecha cambian el orden dentro de esta escena.",
    dragScene: "Cambiar el orden de la escena {{number}}", dragSceneHint: "Arrastra para cambiar el orden. Usa las flechas arriba y abajo con el teclado.", close: "Cerrar",
    createScene: "Crear escena", createCover: "Crear portada", coverEditorPending: "La portada se abrirá más adelante en un editor independiente.",
    storyStart: "Inicio de la historia", storyEnd: "Fin de la historia", noScenes: "Todavía no hay escenas", sceneEdgeHint: "Continúa la historia o prepara su portada.",
    sceneCarousel: "Escenas de la historia", swipeScenes: "Desliza a izquierda o derecha para cambiar de escena", sceneTools: "Herramientas de la escena",
    allStories: "Todas las historias", untitledStory: "Historia sin título", saving: "Guardando", saved: "Guardado", openScene: "Abrir escena",
    downloadScene: "Descargar escena", renderingScene: "Renderizando la escena…", renderSceneError: "No se pudo renderizar la escena. Inténtalo de nuevo.",
    renderVersions: "Versiones guardadas", versionCurrent: "Actual", versionStale: "Obsoleta",
    renderUnsupported: "Actualmente solo se pueden descargar escenas con una foto o un vídeo.",
    renderVersionsHint: "Solo se vuelven a generar los resultados afectados. Las descargas siempre usan la edición actual.",
    renderVersionChanged: "La escena ha cambiado. Vuelve a descargarla para generar la versión actual.",
    versionQueued: "En cola", versionReady: "Lista", versionFailed: "No completada", versionLoading: "Cargando versiones…",
    versionLoadError: "No se pudieron comprobar las versiones. Inténtalo de nuevo en breve.", versionEmpty: "Todavía no hay versiones guardadas.", versionDetails: "Detalles de la versión",
    downloadVideo: "Solo vídeo", downloadAudio: "Solo audio", downloadCombined: "Vídeo con audio",
    noAudioTrack: "Este vídeo no tiene pista de audio.", downloadPreparedFile: "Descargar archivo preparado", muteVideo: "Silenciar", unmuteVideo: "Activar sonido",
    renderQueueTimeout: "El renderizado no comenzó. Comprueba que el proceso de renderizado esté en ejecución e inténtalo de nuevo.",
    renderSceneTimeout: "El renderizado está tardando demasiado. Intenta descargar la escena de nuevo en breve.",
  },
} as const;

export type EditorCopy = { readonly [Key in keyof typeof copies.en]: string };
export function getEditorCopy(locale: Locale): EditorCopy { return copies[locale]; }

export function getEditorOperationError(copy: EditorCopy, error: unknown): string {
  const status = typeof error === "object" && error !== null && "status" in error ? error.status : undefined;
  if (status === 413) return copy.uploadTooLarge;
  if (status === 415) return copy.uploadUnsupported;
  if (status === 422) return copy.uploadUnreadable;
  return copy.operationError;
}

export function getSceneOrderError(copy: EditorCopy, error: unknown): string {
  const code = typeof error === "object" && error !== null && "code" in error ? error.code : undefined;
  return code === "story_revision_conflict" ? copy.sceneOrderChanged : copy.sceneOrderError;
}

export function getMaterialMoveError(copy: EditorCopy, error: unknown): string {
  const code = typeof error === "object" && error !== null && "code" in error ? error.code : undefined;
  return code === "story_revision_conflict" ? copy.materialMoveChanged : copy.materialMoveError;
}
