export const supportedLocales = ["en", "ru", "sr-Latn"] as const;
export type Locale = (typeof supportedLocales)[number];

export const localeOptions: readonly { locale: Locale; label: string; shortLabel: string }[] = [
  { locale: "en", label: "English", shortLabel: "EN" },
  { locale: "ru", label: "Русский", shortLabel: "RU" },
  { locale: "sr-Latn", label: "Srpski", shortLabel: "SR" },
];

type PluralMessage = Partial<Record<Intl.LDMLPluralRule, string>> & { other: string };
type Message = string | PluralMessage;

const en = {
  "common.error": "Something went wrong. Please try again.",
  "common.status.draft": "Draft",
  "common.status.rendering": "Rendering",
  "common.status.ready": "Ready",
  "common.status.publishing": "Publishing",
  "common.status.published": "Published",
  "language.label": "Language",
  "web.api.online": "API online",
  "web.api.offline": "API offline",
  "web.welcome.eyebrow": "Your production space",
  "web.welcome.title.first": "Turn raw moments into",
  "web.welcome.title.second": "finished stories.",
  "web.welcome.copy": "Start with a lightweight studio for scenes, narration, music and publishing. The workflow grows with the product.",
  "web.welcome.name.label": "Your name",
  "web.welcome.name.placeholder": "What should we call you?",
  "web.welcome.creating": "Creating…",
  "web.welcome.enter": "Enter studio →",
  "web.sidebar.workspace": "Workspace",
  "web.sidebar.stories": "Stories",
  "web.sidebar.assets": "Assets",
  "web.sidebar.connections": "Connections",
  "web.sidebar.foundation": "MVP foundation",
  "web.sidebar.memory": "In-memory data",
  "web.library.eyebrow": "Production library",
  "web.library.title": "Your stories",
  "web.library.storyTitle.label": "Story title",
  "web.library.storyTitle.placeholder": "New story title",
  "web.library.newStory": "+ New story",
  "web.library.sceneCount": { one: "{{count}} scene", other: "{{count}} scenes" },
  "web.library.empty": "Create your first story to open the editor.",
  "web.editor.eyebrow": "Story editor",
  "web.editor.select": "Select a story",
  "web.editor.previewStory": "Preview story",
  "web.editor.scenes": "Scenes",
  "web.editor.firstScene": "First scene",
  "web.editor.addScene": "+ Add scene",
  "web.editor.scenePreview": "Your scene preview",
  "web.editor.preview": "Preview",
  "web.editor.settings": "Scene settings",
  "web.editor.title": "Title",
  "web.editor.addTitle": "Add a title",
  "web.editor.renderer": "Renderer",
  "web.editor.chooseRenderer": "Choose renderer",
  "web.editor.timeline": "Timeline",
  "mobile.companion": "MOBILE COMPANION",
  "mobile.hero.label": "YOUR STORIES",
  "mobile.hero.title": "Carry the studio\nwith you.",
  "mobile.hero.copy": "Review stories, track production and capture new material while the full editor stays on the web.",
  "mobile.recent": "Recent",
  "mobile.viewAll": "View all",
  "mobile.createStory": "＋ Create a story",
  "mobile.story.beijing": "Beijing in spring",
  "mobile.story.sea": "Weekend by the sea",
  "mobile.sceneCount": { one: "{{count}} scene", other: "{{count}} scenes" },
} satisfies Record<string, Message>;

export type TranslationKey = keyof typeof en;

const ru: Record<TranslationKey, Message> = {
  "common.error": "Что-то пошло не так. Попробуйте ещё раз.",
  "common.status.draft": "Черновик",
  "common.status.rendering": "Рендеринг",
  "common.status.ready": "Готово",
  "common.status.publishing": "Публикация",
  "common.status.published": "Опубликовано",
  "language.label": "Язык",
  "web.api.online": "API доступен",
  "web.api.offline": "API недоступен",
  "web.welcome.eyebrow": "Ваше пространство для производства",
  "web.welcome.title.first": "Превращайте моменты в",
  "web.welcome.title.second": "готовые истории.",
  "web.welcome.copy": "Начните с простой студии для сцен, озвучки, музыки и публикации. Процесс будет развиваться вместе с продуктом.",
  "web.welcome.name.label": "Ваше имя",
  "web.welcome.name.placeholder": "Как к вам обращаться?",
  "web.welcome.creating": "Создаём…",
  "web.welcome.enter": "Войти в студию →",
  "web.sidebar.workspace": "Пространство",
  "web.sidebar.stories": "Истории",
  "web.sidebar.assets": "Материалы",
  "web.sidebar.connections": "Подключения",
  "web.sidebar.foundation": "Основа MVP",
  "web.sidebar.memory": "Данные в памяти",
  "web.library.eyebrow": "Библиотека производства",
  "web.library.title": "Ваши истории",
  "web.library.storyTitle.label": "Название истории",
  "web.library.storyTitle.placeholder": "Название новой истории",
  "web.library.newStory": "+ Новая история",
  "web.library.sceneCount": { one: "{{count}} сцена", few: "{{count}} сцены", many: "{{count}} сцен", other: "{{count}} сцены" },
  "web.library.empty": "Создайте первую историю, чтобы открыть редактор.",
  "web.editor.eyebrow": "Редактор истории",
  "web.editor.select": "Выберите историю",
  "web.editor.previewStory": "Просмотреть историю",
  "web.editor.scenes": "Сцены",
  "web.editor.firstScene": "Первая сцена",
  "web.editor.addScene": "+ Добавить сцену",
  "web.editor.scenePreview": "Предпросмотр сцены",
  "web.editor.preview": "Предпросмотр",
  "web.editor.settings": "Настройки сцены",
  "web.editor.title": "Заголовок",
  "web.editor.addTitle": "Добавить заголовок",
  "web.editor.renderer": "Рендер",
  "web.editor.chooseRenderer": "Выберите рендер",
  "web.editor.timeline": "Таймлайн",
  "mobile.companion": "МОБИЛЬНОЕ ПРИЛОЖЕНИЕ",
  "mobile.hero.label": "ВАШИ ИСТОРИИ",
  "mobile.hero.title": "Студия всегда\nс вами.",
  "mobile.hero.copy": "Просматривайте истории, следите за производством и добавляйте материалы, пока полный редактор остаётся в веб-приложении.",
  "mobile.recent": "Недавние",
  "mobile.viewAll": "Все",
  "mobile.createStory": "＋ Создать историю",
  "mobile.story.beijing": "Весна в Пекине",
  "mobile.story.sea": "Выходные у моря",
  "mobile.sceneCount": { one: "{{count}} сцена", few: "{{count}} сцены", many: "{{count}} сцен", other: "{{count}} сцены" },
};

const srLatn: Record<TranslationKey, Message> = {
  "common.error": "Došlo je do greške. Pokušajte ponovo.",
  "common.status.draft": "Nacrt",
  "common.status.rendering": "Renderovanje",
  "common.status.ready": "Spremno",
  "common.status.publishing": "Objavljivanje",
  "common.status.published": "Objavljeno",
  "language.label": "Jezik",
  "web.api.online": "API je dostupan",
  "web.api.offline": "API nije dostupan",
  "web.welcome.eyebrow": "Vaš produkcijski prostor",
  "web.welcome.title.first": "Pretvorite trenutke u",
  "web.welcome.title.second": "gotove priče.",
  "web.welcome.copy": "Počnite sa jednostavnim studiom za scene, naraciju, muziku i objavljivanje. Proces raste zajedno sa proizvodom.",
  "web.welcome.name.label": "Vaše ime",
  "web.welcome.name.placeholder": "Kako da vam se obraćamo?",
  "web.welcome.creating": "Kreiranje…",
  "web.welcome.enter": "Uđite u studio →",
  "web.sidebar.workspace": "Radni prostor",
  "web.sidebar.stories": "Priče",
  "web.sidebar.assets": "Materijali",
  "web.sidebar.connections": "Povezivanja",
  "web.sidebar.foundation": "MVP osnova",
  "web.sidebar.memory": "Podaci u memoriji",
  "web.library.eyebrow": "Produkcijska biblioteka",
  "web.library.title": "Vaše priče",
  "web.library.storyTitle.label": "Naslov priče",
  "web.library.storyTitle.placeholder": "Naslov nove priče",
  "web.library.newStory": "+ Nova priča",
  "web.library.sceneCount": { one: "{{count}} scena", few: "{{count}} scene", other: "{{count}} scena" },
  "web.library.empty": "Kreirajte prvu priču da otvorite editor.",
  "web.editor.eyebrow": "Editor priče",
  "web.editor.select": "Izaberite priču",
  "web.editor.previewStory": "Pregled priče",
  "web.editor.scenes": "Scene",
  "web.editor.firstScene": "Prva scena",
  "web.editor.addScene": "+ Dodaj scenu",
  "web.editor.scenePreview": "Pregled scene",
  "web.editor.preview": "Pregled",
  "web.editor.settings": "Podešavanja scene",
  "web.editor.title": "Naslov",
  "web.editor.addTitle": "Dodajte naslov",
  "web.editor.renderer": "Renderer",
  "web.editor.chooseRenderer": "Izaberite renderer",
  "web.editor.timeline": "Vremenska linija",
  "mobile.companion": "MOBILNI PRATILAC",
  "mobile.hero.label": "VAŠE PRIČE",
  "mobile.hero.title": "Ponesite studio\nsa sobom.",
  "mobile.hero.copy": "Pregledajte priče, pratite produkciju i dodajte materijale dok kompletan editor ostaje na vebu.",
  "mobile.recent": "Nedavno",
  "mobile.viewAll": "Prikaži sve",
  "mobile.createStory": "＋ Kreiraj priču",
  "mobile.story.beijing": "Proleće u Pekingu",
  "mobile.story.sea": "Vikend pored mora",
  "mobile.sceneCount": { one: "{{count}} scena", few: "{{count}} scene", other: "{{count}} scena" },
};

const messages: Record<Locale, Record<TranslationKey, Message>> = { en, ru, "sr-Latn": srLatn };

export function normalizeLocale(locale: string | null | undefined): Locale {
  const normalized = locale?.toLowerCase();
  if (normalized?.startsWith("ru")) return "ru";
  if (normalized?.startsWith("sr")) return "sr-Latn";
  return "en";
}

export function translate(locale: Locale, key: TranslationKey, params: Record<string, string | number> = {}): string {
  const message = messages[locale][key];
  const template = typeof message === "string"
    ? message
    : message[new Intl.PluralRules(locale).select(Number(params.count ?? 0))] ?? message.other;

  return template.replace(/{{(\w+)}}/g, (_match, name: string) => String(params[name] ?? ""));
}
