import { profileLanguages, type ProfileLanguage } from "@storyteller/domain";

export const supportedLocales = profileLanguages;
export type Locale = ProfileLanguage;

export const localeOptions: readonly { locale: Locale; label: string; shortLabel: string }[] = [
  { locale: "en", label: "English", shortLabel: "EN" },
  { locale: "ru", label: "Русский", shortLabel: "RU" },
  { locale: "sr-Latn", label: "Srpski", shortLabel: "SR" },
  { locale: "es", label: "Español", shortLabel: "ES" },
];

type PluralMessage = Partial<Record<Intl.LDMLPluralRule, string>> & { other: string };
type Message = string | PluralMessage;

const en = {
  "common.error": "Something went wrong. Please try again.",
  "common.status.draft": "Draft",
  "common.status.rendering": "Rendering",
  "common.status.ready": "Ready",
  "common.status.publishing": "Publishing",
  "common.status.published": "Published",
  "language.label": "Language",
  "language.saveError": "Could not save the language. Please try again.",
  "profile.open": "Open profile",
  "profile.eyebrow": "Account settings",
  "profile.title": "Your profile",
  "profile.name": "Name",
  "profile.email": "Email",
  "profile.languageHint": "This language is used across the site and web studios.",
  "profile.back": "Back to studios",
  "web.api.online": "API online",
  "web.api.offline": "API offline",
  "web.welcome.eyebrow": "Your production space",
  "web.welcome.title.first": "Turn raw moments into",
  "web.welcome.title.second": "finished stories.",
  "web.welcome.copy": "Start with a lightweight studio for scenes, narration, music and publishing. The workflow grows with the product.",
  "web.welcome.name.label": "Your name",
  "web.welcome.name.placeholder": "What should we call you?",
  "web.welcome.email.label": "Email",
  "web.welcome.email.placeholder": "you@example.com",
  "web.welcome.password.label": "Password",
  "web.welcome.password.placeholder": "At least 10 characters",
  "web.welcome.creating": "Creating…",
  "web.welcome.enter": "Enter studio →",
  "web.welcome.login": "Sign in →",
  "web.welcome.signingIn": "Signing in…",
  "web.welcome.nameNeeded": "This email is new. Tell us how to address you to create your profile.",
  "web.welcome.haveAccount": "Already have an account? Sign in",
  "web.welcome.needAccount": "New here? Create a profile",
  "web.library.eyebrow": "Production library",
  "web.library.title": "Your stories",
  "web.library.storyTitle.label": "Story title",
  "web.library.storyTitle.placeholder": "New story title",
  "web.library.newStory": "+ New story",
  "web.library.sceneCount": { one: "{{count}} scene", other: "{{count}} scenes" },
  "web.library.empty": "Create your first story.",
  "web.access.loading": "Checking access…",
  "web.access.deniedTitle": "Studio access is unavailable",
  "web.access.deniedBody": "This account does not currently have access to this action or section.",
  "web.access.errorBody": "We could not verify access. Please try again.",
  "web.story.back": "All stories",
  "web.story.eyebrow": "Story",
  "web.story.empty": "This story is empty. Scene editing will appear here when it is implemented.",
  "web.story.loading": "Loading story…",
  "web.editor.eyebrow": "Story editor",
  "web.editor.select": "Select a story",
  "web.editor.previewStory": "Preview story",
  "web.editor.scenes": "Scenes",
  "web.editor.firstScene": "First scene",
  "web.editor.addScene": "+ Add scene",
  "web.editor.scenePreview": "Your scene preview",
  "web.editor.preview": "Preview",
  "web.editor.settings": "Scene settings",
  "web.editor.title": "Title",
  "web.editor.addTitle": "Add a title",
  "web.editor.renderer": "Renderer",
  "web.editor.chooseRenderer": "Choose renderer",
  "web.editor.timeline": "Timeline",
  "mobile.companion": "MOBILE COMPANION",
  "mobile.hero.label": "YOUR STORIES",
  "mobile.hero.title": "Carry the studio\nwith you.",
  "mobile.hero.copy": "Review stories, track production and capture new material while the full editor stays on the web.",
  "mobile.recent": "Recent",
  "mobile.viewAll": "View all",
  "mobile.createStory": "＋ Create a story",
  "mobile.story.beijing": "Beijing in spring",
  "mobile.story.sea": "Weekend by the sea",
  "mobile.sceneCount": { one: "{{count}} scene", other: "{{count}} scenes" },
} satisfies Record<string, Message>;

export type TranslationKey = keyof typeof en;

const ru: Record<TranslationKey, Message> = {
  "common.error": "Что-то пошло не так. Попробуйте ещё раз.",
  "common.status.draft": "Черновик",
  "common.status.rendering": "Рендеринг",
  "common.status.ready": "Готово",
  "common.status.publishing": "Публикация",
  "common.status.published": "Опубликовано",
  "language.label": "Язык",
  "language.saveError": "Не удалось сохранить язык. Попробуйте ещё раз.",
  "profile.open": "Открыть профиль",
  "profile.eyebrow": "Настройки аккаунта",
  "profile.title": "Ваш профиль",
  "profile.name": "Имя",
  "profile.email": "Email",
  "profile.languageHint": "Этот язык используется на сайте и во всех веб-студиях.",
  "profile.back": "Назад к студиям",
  "web.api.online": "API доступен",
  "web.api.offline": "API недоступен",
  "web.welcome.eyebrow": "Ваше пространство для производства",
  "web.welcome.title.first": "Превращайте моменты в",
  "web.welcome.title.second": "готовые истории.",
  "web.welcome.copy": "Начните с простой студии для сцен, озвучки, музыки и публикации. Процесс будет развиваться вместе с продуктом.",
  "web.welcome.name.label": "Ваше имя",
  "web.welcome.name.placeholder": "Как к вам обращаться?",
  "web.welcome.email.label": "Email",
  "web.welcome.email.placeholder": "you@example.com",
  "web.welcome.password.label": "Пароль",
  "web.welcome.password.placeholder": "Не менее 10 символов",
  "web.welcome.creating": "Создаём…",
  "web.welcome.enter": "Войти в студию →",
  "web.welcome.login": "Войти →",
  "web.welcome.signingIn": "Входим…",
  "web.welcome.nameNeeded": "Этот email ещё не зарегистрирован. Укажите, как к вам обращаться, и мы создадим профиль.",
  "web.welcome.haveAccount": "Уже есть профиль? Войти",
  "web.welcome.needAccount": "Впервые здесь? Создать профиль",
  "web.library.eyebrow": "Библиотека производства",
  "web.library.title": "Ваши истории",
  "web.library.storyTitle.label": "Название истории",
  "web.library.storyTitle.placeholder": "Название новой истории",
  "web.library.newStory": "+ Новая история",
  "web.library.sceneCount": { one: "{{count}} сцена", few: "{{count}} сцены", many: "{{count}} сцен", other: "{{count}} сцены" },
  "web.library.empty": "Создайте первую историю.",
  "web.access.loading": "Проверяем доступ…",
  "web.access.deniedTitle": "Доступ к студии закрыт",
  "web.access.deniedBody": "Сейчас у этого аккаунта нет доступа к действию или разделу.",
  "web.access.errorBody": "Не удалось проверить доступ. Попробуйте ещё раз.",
  "web.story.back": "Все истории",
  "web.story.eyebrow": "История",
  "web.story.empty": "Эта история пока пуста. Редактирование сцен появится здесь, когда будет реализовано.",
  "web.story.loading": "Загружаем историю…",
  "web.editor.eyebrow": "Редактор истории",
  "web.editor.select": "Выберите историю",
  "web.editor.previewStory": "Просмотреть историю",
  "web.editor.scenes": "Сцены",
  "web.editor.firstScene": "Первая сцена",
  "web.editor.addScene": "+ Добавить сцену",
  "web.editor.scenePreview": "Предпросмотр сцены",
  "web.editor.preview": "Предпросмотр",
  "web.editor.settings": "Настройки сцены",
  "web.editor.title": "Заголовок",
  "web.editor.addTitle": "Добавить заголовок",
  "web.editor.renderer": "Рендер",
  "web.editor.chooseRenderer": "Выберите рендер",
  "web.editor.timeline": "Таймлайн",
  "mobile.companion": "МОБИЛЬНОЕ ПРИЛОЖЕНИЕ",
  "mobile.hero.label": "ВАШИ ИСТОРИИ",
  "mobile.hero.title": "Студия всегда\nс вами.",
  "mobile.hero.copy": "Просматривайте истории, следите за производством и добавляйте материалы, пока полный редактор остаётся в веб-приложении.",
  "mobile.recent": "Недавние",
  "mobile.viewAll": "Все",
  "mobile.createStory": "＋ Создать историю",
  "mobile.story.beijing": "Весна в Пекине",
  "mobile.story.sea": "Выходные у моря",
  "mobile.sceneCount": { one: "{{count}} сцена", few: "{{count}} сцены", many: "{{count}} сцен", other: "{{count}} сцены" },
};

const srLatn: Record<TranslationKey, Message> = {
  "common.error": "Došlo je do greške. Pokušajte ponovo.",
  "common.status.draft": "Nacrt",
  "common.status.rendering": "Renderovanje",
  "common.status.ready": "Spremno",
  "common.status.publishing": "Objavljivanje",
  "common.status.published": "Objavljeno",
  "language.label": "Jezik",
  "language.saveError": "Nije moguće sačuvati jezik. Pokušajte ponovo.",
  "profile.open": "Otvori profil",
  "profile.eyebrow": "Podešavanja naloga",
  "profile.title": "Vaš profil",
  "profile.name": "Ime",
  "profile.email": "Email",
  "profile.languageHint": "Ovaj jezik se koristi na sajtu i u svim veb studijima.",
  "profile.back": "Nazad na studije",
  "web.api.online": "API je dostupan",
  "web.api.offline": "API nije dostupan",
  "web.welcome.eyebrow": "Vaš produkcijski prostor",
  "web.welcome.title.first": "Pretvorite trenutke u",
  "web.welcome.title.second": "gotove priče.",
  "web.welcome.copy": "Počnite sa jednostavnim studiom za scene, naraciju, muziku i objavljivanje. Proces raste zajedno sa proizvodom.",
  "web.welcome.name.label": "Vaše ime",
  "web.welcome.name.placeholder": "Kako da vam se obraćamo?",
  "web.welcome.email.label": "Email",
  "web.welcome.email.placeholder": "you@example.com",
  "web.welcome.password.label": "Lozinka",
  "web.welcome.password.placeholder": "Najmanje 10 znakova",
  "web.welcome.creating": "Kreiranje…",
  "web.welcome.enter": "Uđite u studio →",
  "web.welcome.login": "Prijavite se →",
  "web.welcome.signingIn": "Prijavljivanje…",
  "web.welcome.nameNeeded": "Ovaj email je nov. Recite nam kako da vam se obraćamo da bismo kreirali profil.",
  "web.welcome.haveAccount": "Već imate profil? Prijavite se",
  "web.welcome.needAccount": "Novi ste? Kreirajte profil",
  "web.library.eyebrow": "Produkcijska biblioteka",
  "web.library.title": "Vaše priče",
  "web.library.storyTitle.label": "Naslov priče",
  "web.library.storyTitle.placeholder": "Naslov nove priče",
  "web.library.newStory": "+ Nova priča",
  "web.library.sceneCount": { one: "{{count}} scena", few: "{{count}} scene", other: "{{count}} scena" },
  "web.library.empty": "Kreirajte prvu priču.",
  "web.access.loading": "Proveravamo pristup…",
  "web.access.deniedTitle": "Pristup studiju nije dostupan",
  "web.access.deniedBody": "Ovaj nalog trenutno nema pristup ovoj radnji ili odeljku.",
  "web.access.errorBody": "Nije moguće proveriti pristup. Pokušajte ponovo.",
  "web.story.back": "Sve priče",
  "web.story.eyebrow": "Priča",
  "web.story.empty": "Ova priča je prazna. Uređivanje scena će se pojaviti ovde kada bude implementirano.",
  "web.story.loading": "Učitavanje priče…",
  "web.editor.eyebrow": "Editor priče",
  "web.editor.select": "Izaberite priču",
  "web.editor.previewStory": "Pregled priče",
  "web.editor.scenes": "Scene",
  "web.editor.firstScene": "Prva scena",
  "web.editor.addScene": "+ Dodaj scenu",
  "web.editor.scenePreview": "Pregled scene",
  "web.editor.preview": "Pregled",
  "web.editor.settings": "Podešavanja scene",
  "web.editor.title": "Naslov",
  "web.editor.addTitle": "Dodajte naslov",
  "web.editor.renderer": "Renderer",
  "web.editor.chooseRenderer": "Izaberite renderer",
  "web.editor.timeline": "Vremenska linija",
  "mobile.companion": "MOBILNI PRATILAC",
  "mobile.hero.label": "VAŠE PRIČE",
  "mobile.hero.title": "Ponesite studio\nsa sobom.",
  "mobile.hero.copy": "Pregledajte priče, pratite produkciju i dodajte materijale dok kompletan editor ostaje na vebu.",
  "mobile.recent": "Nedavno",
  "mobile.viewAll": "Prikaži sve",
  "mobile.createStory": "＋ Kreiraj priču",
  "mobile.story.beijing": "Proleće u Pekingu",
  "mobile.story.sea": "Vikend pored mora",
  "mobile.sceneCount": { one: "{{count}} scena", few: "{{count}} scene", other: "{{count}} scena" },
};

const es: Record<TranslationKey, Message> = {
  "common.error": "Algo salió mal. Inténtalo de nuevo.",
  "common.status.draft": "Borrador",
  "common.status.rendering": "Renderizando",
  "common.status.ready": "Listo",
  "common.status.publishing": "Publicando",
  "common.status.published": "Publicado",
  "language.label": "Idioma",
  "language.saveError": "No se pudo guardar el idioma. Inténtalo de nuevo.",
  "profile.open": "Abrir perfil",
  "profile.eyebrow": "Configuración de la cuenta",
  "profile.title": "Tu perfil",
  "profile.name": "Nombre",
  "profile.email": "Correo electrónico",
  "profile.languageHint": "Este idioma se usa en el sitio y en todos los estudios web.",
  "profile.back": "Volver a los estudios",
  "web.api.online": "API disponible",
  "web.api.offline": "API no disponible",
  "web.welcome.eyebrow": "Tu espacio de producción",
  "web.welcome.title.first": "Convierte momentos sin editar en",
  "web.welcome.title.second": "historias terminadas.",
  "web.welcome.copy": "Empieza con un estudio sencillo para escenas, narración, música y publicación. El flujo de trabajo crece con el producto.",
  "web.welcome.name.label": "Tu nombre",
  "web.welcome.name.placeholder": "¿Cómo quieres que te llamemos?",
  "web.welcome.email.label": "Correo electrónico",
  "web.welcome.email.placeholder": "tu@ejemplo.com",
  "web.welcome.password.label": "Contraseña",
  "web.welcome.password.placeholder": "Al menos 10 caracteres",
  "web.welcome.creating": "Creando…",
  "web.welcome.enter": "Entrar al estudio →",
  "web.welcome.login": "Iniciar sesión →",
  "web.welcome.signingIn": "Iniciando sesión…",
  "web.welcome.nameNeeded": "Este correo es nuevo. Dinos cómo quieres que te llamemos para crear tu perfil.",
  "web.welcome.haveAccount": "¿Ya tienes una cuenta? Inicia sesión",
  "web.welcome.needAccount": "¿Es tu primera vez? Crea un perfil",
  "web.library.eyebrow": "Biblioteca de producción",
  "web.library.title": "Tus historias",
  "web.library.storyTitle.label": "Título de la historia",
  "web.library.storyTitle.placeholder": "Título de la nueva historia",
  "web.library.newStory": "+ Nueva historia",
  "web.library.sceneCount": { one: "{{count}} escena", other: "{{count}} escenas" },
  "web.library.empty": "Crea tu primera historia.",
  "web.access.loading": "Comprobando el acceso…",
  "web.access.deniedTitle": "El acceso al estudio no está disponible",
  "web.access.deniedBody": "Esta cuenta no tiene acceso actualmente a esta acción o sección.",
  "web.access.errorBody": "No pudimos comprobar el acceso. Inténtalo de nuevo.",
  "web.story.back": "Todas las historias",
  "web.story.eyebrow": "Historia",
  "web.story.empty": "Esta historia está vacía. La edición de escenas aparecerá aquí cuando esté implementada.",
  "web.story.loading": "Cargando la historia…",
  "web.editor.eyebrow": "Editor de historias",
  "web.editor.select": "Selecciona una historia",
  "web.editor.previewStory": "Vista previa de la historia",
  "web.editor.scenes": "Escenas",
  "web.editor.firstScene": "Primera escena",
  "web.editor.addScene": "+ Añadir escena",
  "web.editor.scenePreview": "Vista previa de la escena",
  "web.editor.preview": "Vista previa",
  "web.editor.settings": "Ajustes de la escena",
  "web.editor.title": "Título",
  "web.editor.addTitle": "Añadir un título",
  "web.editor.renderer": "Renderizador",
  "web.editor.chooseRenderer": "Elegir renderizador",
  "web.editor.timeline": "Línea de tiempo",
  "mobile.companion": "APLICACIÓN MÓVIL",
  "mobile.hero.label": "TUS HISTORIAS",
  "mobile.hero.title": "Lleva el estudio\ncontigo.",
  "mobile.hero.copy": "Revisa historias, sigue la producción y captura nuevos materiales mientras el editor completo permanece en la web.",
  "mobile.recent": "Recientes",
  "mobile.viewAll": "Ver todo",
  "mobile.createStory": "＋ Crear una historia",
  "mobile.story.beijing": "Pekín en primavera",
  "mobile.story.sea": "Fin de semana junto al mar",
  "mobile.sceneCount": { one: "{{count}} escena", other: "{{count}} escenas" },
};

const messages: Record<Locale, Record<TranslationKey, Message>> = { en, ru, "sr-Latn": srLatn, es };

export function normalizeLocale(locale: string | null | undefined): Locale {
  const normalized = locale?.toLowerCase();
  if (normalized?.startsWith("ru")) return "ru";
  if (normalized?.startsWith("sr")) return "sr-Latn";
  if (normalized?.startsWith("es")) return "es";
  return "en";
}

export function translate(locale: Locale, key: TranslationKey, params: Record<string, string | number> = {}): string {
  const message = messages[locale][key];
  const template = typeof message === "string"
    ? message
    : message[new Intl.PluralRules(locale).select(Number(params.count ?? 0))] ?? message.other;

  return template.replace(/{{(\w+)}}/g, (_match, name: string) => String(params[name] ?? ""));
}
